project_id = "iyqyvvfibmzxujiwznkb"

[api]
enabled = true
port = 54321

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[functions.analyze-listing]
verify_jwt = true

[functions.generate-video]
verify_jwt = true

[edge-runtime]
policy = "per_worker"