// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iyqyvvfibmzxujiwznkb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml5cXl2dmZpYm16eHVqaXd6bmtiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyMTI4NDAsImV4cCI6MjA3Mjc4ODg0MH0.kDouNSNn92pWhbcLshHkiv5Io61zMAGn7Pg4JImSSZA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});